#lang racket
(define (make-withdraw balance)
  (lambda (amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount)) balance)
        ("Insufficient funds")
        )
    )
  )
(define w1 (make-withdraw 100))