#lang Racket
(define x (list 1 2))
(define (count-leaves x)
  (cond ((null? x) 0)
        ((not (pair? x)) 1)
        (else (+ (count-leaves (car x))
                 (count-leaves (cdr x)
                 )))
    )
  )
;(count-leaves x)